# Generated by Django 6.1 on 2026-08-31 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='default_job', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=50)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('success_items', models.IntegerField(default=0)),
                ('review_needed_items', models.IntegerField(default=0)),
                ('last_processed_product_id', models.BigIntegerField(default=0)),
                ('current_index', models.IntegerField(default=0)),
                ('chunk_size', models.IntegerField(default=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Batch Processing Job',
                'verbose_name_plural': 'Batch Processing Jobs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('product_category', models.CharField(blank=True, default='', max_length=255)),
                ('product_sub_category', models.CharField(blank=True, default='', max_length=255)),
                ('collection_name', models.CharField(blank=True, default='', max_length=255)),
                ('color_collection', models.CharField(blank=True, default='', max_length=255)),
                ('product_color', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('product_description', models.TextField(blank=True, default='')),
                ('bullets', models.TextField(blank=True, default='')),
                ('set_includes', models.TextField(blank=True, default='')),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, default='')),
                ('product_dimensions', models.TextField(blank=True, default='')),
                ('assembly_required', models.CharField(blank=True, default='', max_length=50)),
                ('is_set', models.CharField(blank=True, default='', max_length=50)),
                ('stackable', models.CharField(blank=True, default='', max_length=50)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('primary_image_url', models.CharField(blank=True, default='', max_length=1000)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('shipping_method', models.CharField(blank=True, default='', max_length=100)),
                ('total_box_count', models.IntegerField(blank=True, default=1, null=True)),
                ('pallet_count', models.FloatField(blank=True, null=True)),
                ('shipping_weight', models.FloatField(blank=True, null=True)),
                ('total_cbm', models.FloatField(blank=True, null=True)),
                ('package_dimensions', models.TextField(blank=True, default='')),
                ('product_url', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_gid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Shopify Attribute',
                'verbose_name_plural': 'Shopify Attributes',
            },
        ),
        migrations.CreateModel(
            name='ShopifyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_gid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(db_index=True, max_length=1000)),
                ('level', models.IntegerField(default=0)),
                ('parent_gid', models.CharField(blank=True, max_length=255, null=True)),
                ('vertical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes_json', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Shopify Category',
                'verbose_name_plural': 'Shopify Categories',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_category_name', models.CharField(blank=True, default='', max_length=1000)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('CLASSIFIED', 'Classified'), ('REQUIRES_REVIEW', 'Requires Review'), ('MANUALLY_OVERRIDDEN', 'Manually Overridden'), ('APPROVED', 'Approved')], db_index=True, default='UNPROCESSED', max_length=50)),
                ('extracted_attributes', models.JSONField(blank=True, default=dict)),
                ('alternative_categories', models.JSONField(blank=True, default=list)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='taxonomy.product')),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='taxonomy.shopifycategory')),
            ],
            options={
                'verbose_name': 'Classification Result',
                'verbose_name_plural': 'Classification Results',
                'ordering': ['product_id'],
            },
        ),
    ]
